/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function formatTex(
  buffer: Buffer,
  options?: FormatTexOptions | undefined | null,
): Promise<Buffer>

export interface FormatTexOptions {
  format?: string
  quality?: number
  effort?: number
}
