/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function formatTex(buffer: Buffer, options?: FormatTexOptions | undefined | null): Promise<FormatTexResult>

export interface FormatTexOptions {
  format?: string
  quality?: number
  effort?: number
}

export interface FormatTexResult {
  format: string
  data: Buffer
}
