packages:
  - .
  - config
  - packages/*

catalog:
  '@biomejs/biome': 2.2.3
  '@types/debug': ^4.1.12
  '@types/node': ^22.18.1
  '@vitest/coverage-v8': ^3.2.4
  debug: ^4.4.1
  smart-buffer: ^4.2.0
  tsup: ^8.0.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  vitest: ^3.2.4
