packages:
  - .
  - config
  - packages/*

catalog:
  '@biomejs/biome': 2.2.3
  '@types/debug': 4.1.12
  '@types/node': ^22.19.0
  '@vitest/coverage-v8': ^3.2.4
  debug: 4.4.1
  smart-buffer: ^4.2.0
  tsup: ^8.5.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - lefthook

nodeLinker: 'hoisted'